[package]
name = "archetypal_core"
version = "0.1.0"
edition = "2018"

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
